services:
  nats:
    image: nats:latest
    command: ['-js', '-sd', '/data']
    ports:
      - '4222:4222'
    volumes:
      - ./data/nats:/data

  redis:
    image: redis:7-alpine
    command:
      - redis-server
      - --requirepass
      - ${REDIS_PASSWORD}
      - --appendonly
      - 'yes'
      - --dir
      - /data
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
